### PR TITLE
Fix broken inspection name

### LINKED ISSUE #328: Typo in usesDyamicPolymorphism
Should be `usesDynamicPolymorphism`
Funnily enough, the typo is consistent all over the code. But it was being used properly written in content, causing it to not fail.

### PR DESCRIPTION
**Pull request by flbulgarelli**
# :dart: Goal

To fix a typo that prevented `UsesDynamicPolymorphism` to be used. 

# :beetle: Fixes

* Fixes #328 

# :eyes: See also

* #211

### CODE REVIEW

**Review by julian-berbel — APPROVED** [review]
Looks good!

File: src/Language/Mulang/Analyzer/EdlQueryCompiler.hs [hunk 1]
```diff
@@ -153,7 +153,7 @@ compileInspection = f
   f "UsesComposition"                  E.Unmatching   = plain usesComposition
   f "UsesComprehension"                E.Unmatching   = f "UsesForComprehension" E.Unmatching
   f "UsesConditional"                  E.Unmatching   = plain usesConditional
-  f "UsesDyamicPolymorphism"           E.Unmatching   = contextual usesDyamicPolymorphism'
+  f "UsesDynamicPolymorphism"           E.Unmatching   = contextual usesDynamicPolymorphism'
```
Comment (julian-berbel) [inline src/Language/Mulang/Analyzer/EdlQueryCompiler.hs:156]: ever so slightly bothered by the indentation here :laughing:

Comment (flbulgarelli) [reply src/Language/Mulang/Analyzer/EdlQueryCompiler.hs:156]: :rofl:
